#!/bin/bash

# Source directory containing the libraries
SOURCE_DIR="/Users/pc/web3/clickHouse/build"

# Create the target directory if it doesn't exist
mkdir -p lib/darwin-aarch64

# List of libraries to copy
libraries=(
    "src/Parsers/libclickhouse_parsers.a"
    "src/Access/Common/libclickhouse_common_access.a"
    "rust/workspace/lib_ch_rust_prql.a"
    "rust/workspace/lib_ch_rust_skim_rust.a"
    "contrib/llvm-project/llvm/lib/libLLVMSupport.a"
    "contrib/llvm-project/llvm/lib/libLLVMDemangle.a"
    "contrib/croaring-cmake/lib_roaring.a"
    "contrib/cppkafka-cmake/lib_cppkafka.a"
    "contrib/librdkafka-cmake/lib_rdkafka.a"
    "contrib/nats-io-cmake/lib_nats_io.a"
    "contrib/cyrus-sasl-cmake/lib_sasl2.a"
    "contrib/krb5-cmake/lib_krb5.a"
    "contrib/nuraft-cmake/lib_nuraft.a"
    "contrib/boost-cmake/lib_boost_coroutine.a"
    "src/Dictionaries/Embedded/libclickhouse_dictionaries_embedded.a"
    "base/poco/MongoDB/lib_poco_mongodb.a"
    "base/poco/Redis/lib_poco_redis.a"
    "src/Common/mysqlxx/libmysqlxx.a"
    "src/libclickhouse_common_io.a"
    "base/base/libcommon.a"
    "base/poco/Foundation/lib_poco_foundation.a"
    "base/poco/Net/lib_poco_net.a"
    "base/poco/NetSSL_OpenSSL/lib_poco_net_ssl.a"
    "base/poco/Util/lib_poco_util.a"
    "base/poco/XML/lib_poco_xml.a"
    "base/poco/JSON/lib_poco_json.a"
    "base/poco/Crypto/lib_poco_crypto.a"
    "contrib/fmtlib-cmake/lib_fmt.a"
    "contrib/abseil-cpp-cmake/libabsl_leak_check.a"
    "contrib/abseil-cpp-cmake/libabsl_die_if_null.a"
    "contrib/abseil-cpp-cmake/libabsl_log_initialize.a"
    "contrib/grpc-cmake/libgrpc.a"
    "contrib/re2-cmake/lib_re2.a"
    "contrib/c-ares-cmake/lib_c-ares.a"
    "contrib/abseil-cpp-cmake/libabsl_statusor.a"
    "contrib/grpc-cmake/libupb_json_lib.a"
    "contrib/grpc-cmake/libupb_textformat_lib.a"
    "contrib/grpc-cmake/libupb_collections_lib.a"
    "contrib/grpc-cmake/libupb.a"
    "contrib/grpc-cmake/libutf8_range_lib.a"
    "contrib/grpc-cmake/libgpr.a"
    "contrib/abseil-cpp-cmake/libabsl_random_distributions.a"
    "contrib/abseil-cpp-cmake/libabsl_random_seed_sequences.a"
    "contrib/abseil-cpp-cmake/libabsl_random_internal_pool_urbg.a"
    "contrib/abseil-cpp-cmake/libabsl_random_internal_randen.a"
    "contrib/abseil-cpp-cmake/libabsl_random_internal_randen_hwaes.a"
    "contrib/abseil-cpp-cmake/libabsl_random_internal_randen_hwaes_impl.a"
    "contrib/abseil-cpp-cmake/libabsl_random_internal_randen_slow.a"
    "contrib/abseil-cpp-cmake/libabsl_random_internal_platform.a"
    "contrib/abseil-cpp-cmake/libabsl_random_internal_seed_material.a"
    "contrib/abseil-cpp-cmake/libabsl_random_seed_gen_exception.a"
    "contrib/grpc-cmake/libaddress_sorting.a"
    "contrib/s2geometry-cmake/lib_s2.a"
    "contrib/abseil-cpp-cmake/libabsl_log_internal_check_op.a"
    "contrib/abseil-cpp-cmake/libabsl_flags_internal.a"
    "contrib/abseil-cpp-cmake/libabsl_flags_marshalling.a"
    "contrib/abseil-cpp-cmake/libabsl_flags_reflection.a"
    "contrib/abseil-cpp-cmake/libabsl_raw_hash_set.a"
    "contrib/abseil-cpp-cmake/libabsl_hashtablez_sampler.a"
    "contrib/abseil-cpp-cmake/libabsl_flags_config.a"
    "contrib/abseil-cpp-cmake/libabsl_flags_program_name.a"
    "contrib/abseil-cpp-cmake/libabsl_flags_private_handle_accessor.a"
    "contrib/abseil-cpp-cmake/libabsl_flags_commandlineflag.a"
    "contrib/abseil-cpp-cmake/libabsl_flags_commandlineflag_internal.a"
    "contrib/abseil-cpp-cmake/libabsl_log_internal_conditions.a"
    "contrib/abseil-cpp-cmake/libabsl_log_internal_message.a"
    "contrib/abseil-cpp-cmake/libabsl_log_internal_nullguard.a"
    "contrib/abseil-cpp-cmake/libabsl_examine_stack.a"
    "contrib/abseil-cpp-cmake/libabsl_log_internal_format.a"
    "contrib/abseil-cpp-cmake/libabsl_log_internal_proto.a"
    "contrib/abseil-cpp-cmake/libabsl_log_internal_log_sink_set.a"
    "contrib/abseil-cpp-cmake/libabsl_log_globals.a"
    "contrib/abseil-cpp-cmake/libabsl_hash.a"
    "contrib/abseil-cpp-cmake/libabsl_bad_variant_access.a"
    "contrib/abseil-cpp-cmake/libabsl_city.a"
    "contrib/abseil-cpp-cmake/libabsl_low_level_hash.a"
    "contrib/abseil-cpp-cmake/libabsl_log_internal_globals.a"
    "contrib/abseil-cpp-cmake/libabsl_log_sink.a"
    "contrib/abseil-cpp-cmake/libabsl_log_entry.a"
    "contrib/abseil-cpp-cmake/libabsl_vlog_config_internal.a"
    "contrib/abseil-cpp-cmake/libabsl_log_internal_fnmatch.a"
    "contrib/abseil-cpp-cmake/libabsl_status.a"
    "contrib/abseil-cpp-cmake/libabsl_cord.a"
    "contrib/abseil-cpp-cmake/libabsl_bad_optional_access.a"
    "contrib/abseil-cpp-cmake/libabsl_cordz_info.a"
    "contrib/abseil-cpp-cmake/libabsl_cord_internal.a"
    "contrib/abseil-cpp-cmake/libabsl_cordz_functions.a"
    "contrib/abseil-cpp-cmake/libabsl_exponential_biased.a"
    "contrib/abseil-cpp-cmake/libabsl_cordz_handle.a"
    "contrib/abseil-cpp-cmake/libabsl_synchronization.a"
    "contrib/abseil-cpp-cmake/libabsl_graphcycles_internal.a"
    "contrib/abseil-cpp-cmake/libabsl_kernel_timeout_internal.a"
    "contrib/abseil-cpp-cmake/libabsl_stacktrace.a"
    "contrib/abseil-cpp-cmake/libabsl_symbolize.a"
    "contrib/abseil-cpp-cmake/libabsl_malloc_internal.a"
    "contrib/abseil-cpp-cmake/libabsl_debugging_internal.a"
    "contrib/abseil-cpp-cmake/libabsl_demangle_internal.a"
    "contrib/abseil-cpp-cmake/libabsl_time.a"
    "contrib/abseil-cpp-cmake/libabsl_civil_time.a"
    "contrib/abseil-cpp-cmake/libabsl_time_zone.a"
    "contrib/abseil-cpp-cmake/libabsl_crc_cord_state.a"
    "contrib/abseil-cpp-cmake/libabsl_crc32c.a"
    "contrib/abseil-cpp-cmake/libabsl_str_format_internal.a"
    "contrib/abseil-cpp-cmake/libabsl_strings.a"
    "contrib/abseil-cpp-cmake/libabsl_strings_internal.a"
    "contrib/abseil-cpp-cmake/libabsl_string_view.a"
    "contrib/abseil-cpp-cmake/libabsl_throw_delegate.a"
    "contrib/abseil-cpp-cmake/libabsl_int128.a"
    "contrib/abseil-cpp-cmake/libabsl_crc_internal.a"
    "contrib/abseil-cpp-cmake/libabsl_crc_cpu_detect.a"
    "contrib/abseil-cpp-cmake/libabsl_base.a"
    "contrib/abseil-cpp-cmake/libabsl_raw_logging_internal.a"
    "contrib/abseil-cpp-cmake/libabsl_log_severity.a"
    "contrib/abseil-cpp-cmake/libabsl_spinlock_wait.a"
    "contrib/abseil-cpp-cmake/libabsl_strerror.a"
    "contrib/cctz-cmake/lib_cctz.a"
    "contrib/cctz-cmake/libtzdata.a"
)

# Copy each library to the target directory
for lib in "${libraries[@]}"; do
    cp "$SOURCE_DIR/$lib" lib/darwin-aarch64/
done

echo "Libraries copied successfully to lib/darwin-aarch64/"
